// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUYbaYUmhWTGgVudQLOMqFBtr0OYjmeHs',
    appId: '1:119600048653:web:ef3209c3aee62928e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    authDomain: 'hu-student-debt.firebaseapp.com',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    measurementId: 'G-FEQH6NBNYZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh0P-6P7pzCPIg1KXjK8M8lXwRaGePqJU',
    appId: '1:119600048653:android:df5d50a270b69085e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    storageBucket: 'hu-student-debt.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgBnxnkN7HLfBvVpksuCKTJagMUF_g-mY',
    appId: '1:119600048653:ios:3730f40a712c75c5e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    iosClientId: '119600048653-2fbedepoj9e1epnos78r34dv4cfr0h3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgBnxnkN7HLfBvVpksuCKTJagMUF_g-mY',
    appId: '1:119600048653:ios:3730f40a712c75c5e38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    iosClientId: '119600048653-2fbedepoj9e1epnos78r34dv4cfr0h3t.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6H7KdE4rjbTKDWisjs1unqqiYkvwHbTA',
    appId: '1:119600048653:web:15c77e0b148d1a8ee38344',
    messagingSenderId: '119600048653',
    projectId: 'hu-student-debt',
    authDomain: 'hu-student-debt.firebaseapp.com',
    storageBucket: 'hu-student-debt.firebasestorage.app',
    measurementId: 'G-Y5YBM9EDWF',
  );
}
