export const DEPARTMENTS = [
  'Accounting and Finance',
  'Architecture',
  'Biology',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Computer Science',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English Language and Literature',
  'Information System',
  'Law',
  'Management',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine',
  'Midwifery',
  'Nursing',
  'Pharmacy',
  'Physics',
  'Public Health',
  'Software Engineering',
  'Statistics',
];
